pipeline {
  agent any 
  tools {
    maven 'maven-3.9.11'
  }
  stages {
    stage('checkout') {
      steps {
        git branch: 'main'
      }
    }
    stage('build') {
      steps {
        bat : 'mvn clean instant'
      }
    }
    stage('test') {
      steps {
        bat : 'test'
      }
    }
  }
}
